// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptRequest) Reset() {
	*x = TranscriptRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptRequest) ProtoMessage() {}

func (x *TranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptRequest.ProtoReflect.Descriptor instead.
func (*TranscriptRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TranscriptRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *TranscriptRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *QueueRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *QueueRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type QueueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*QueueEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueList) Reset() {
	*x = QueueList{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueList) ProtoMessage() {}

func (x *QueueList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueList.ProtoReflect.Descriptor instead.
func (*QueueList) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *QueueList) GetEntries() []*QueueEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type QueueEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueEntry) Reset() {
	*x = QueueEntry{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueEntry) ProtoMessage() {}

func (x *QueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueEntry.ProtoReflect.Descriptor instead.
func (*QueueEntry) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *QueueEntry) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *QueueEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *QueueEntry) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

type RetakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetakeRequest) Reset() {
	*x = RetakeRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetakeRequest) ProtoMessage() {}

func (x *RetakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetakeRequest.ProtoReflect.Descriptor instead.
func (*RetakeRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *RetakeRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RetakeRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *RetakeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ScheduleEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleResponse) GetEntries() []*ScheduleEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ScheduleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Day           string                 `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Room          string                 `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEntry) Reset() {
	*x = ScheduleEntry{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEntry) ProtoMessage() {}

func (x *ScheduleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEntry.ProtoReflect.Descriptor instead.
func (*ScheduleEntry) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleEntry) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *ScheduleEntry) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *ScheduleEntry) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ScheduleEntry) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type UpdateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Day           string                 `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Room          string                 `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduleRequest) Reset() {
	*x = UpdateScheduleRequest{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleRequest) ProtoMessage() {}

func (x *UpdateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateScheduleRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateScheduleRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *UpdateScheduleRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *UpdateScheduleRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type CertificateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentId       string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CertificateType string                 `protobuf:"bytes,2,opt,name=certificate_type,json=certificateType,proto3" json:"certificate_type,omitempty"`
	Details         string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CertificateRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CertificateRequest) GetCertificateType() string {
	if x != nil {
		return x.CertificateType
	}
	return ""
}

func (x *CertificateRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x05admin\"L\n" +
	"\x11TranscriptRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\"E\n" +
	"\fQueueRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\tQueueList\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.admin.QueueEntryR\aentries\"`\n" +
	"\n" +
	"QueueEntry\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\tR\bjoinedAt\"c\n" +
	"\rRetakeRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"0\n" +
	"\x0fScheduleRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"B\n" +
	"\x10ScheduleResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.admin.ScheduleEntryR\aentries\"f\n" +
	"\rScheduleEntry\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x10\n" +
	"\x03day\x18\x02 \x01(\tR\x03day\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x12\n" +
	"\x04room\x18\x04 \x01(\tR\x04room\"n\n" +
	"\x15UpdateScheduleRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x10\n" +
	"\x03day\x18\x02 \x01(\tR\x03day\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x12\n" +
	"\x04room\x18\x04 \x01(\tR\x04room\"x\n" +
	"\x12CertificateRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12)\n" +
	"\x10certificate_type\x18\x02 \x01(\tR\x0fcertificateType\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\a\n" +
	"\x05Empty2\xa7\x03\n" +
	"\fAdminService\x12A\n" +
	"\x17CreateTranscriptRequest\x12\x18.admin.TranscriptRequest\x1a\f.admin.Empty\x12+\n" +
	"\tViewQueue\x12\f.admin.Empty\x1a\x10.admin.QueueList\x12.\n" +
	"\tJoinQueue\x12\x13.admin.QueueRequest\x1a\f.admin.Empty\x124\n" +
	"\x0eRegisterRetake\x12\x14.admin.RetakeRequest\x1a\f.admin.Empty\x12>\n" +
	"\vGetSchedule\x12\x16.admin.ScheduleRequest\x1a\x17.admin.ScheduleResponse\x12<\n" +
	"\x0eUpdateSchedule\x12\x1c.admin.UpdateScheduleRequest\x1a\f.admin.Empty\x12C\n" +
	"\x18SubmitCertificateRequest\x12\x19.admin.CertificateRequest\x1a\f.admin.EmptyB\rZ\vadmin/pb;pbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_admin_proto_goTypes = []any{
	(*TranscriptRequest)(nil),     // 0: admin.TranscriptRequest
	(*QueueRequest)(nil),          // 1: admin.QueueRequest
	(*QueueList)(nil),             // 2: admin.QueueList
	(*QueueEntry)(nil),            // 3: admin.QueueEntry
	(*RetakeRequest)(nil),         // 4: admin.RetakeRequest
	(*ScheduleRequest)(nil),       // 5: admin.ScheduleRequest
	(*ScheduleResponse)(nil),      // 6: admin.ScheduleResponse
	(*ScheduleEntry)(nil),         // 7: admin.ScheduleEntry
	(*UpdateScheduleRequest)(nil), // 8: admin.UpdateScheduleRequest
	(*CertificateRequest)(nil),    // 9: admin.CertificateRequest
	(*Empty)(nil),                 // 10: admin.Empty
}
var file_admin_proto_depIdxs = []int32{
	3,  // 0: admin.QueueList.entries:type_name -> admin.QueueEntry
	7,  // 1: admin.ScheduleResponse.entries:type_name -> admin.ScheduleEntry
	0,  // 2: admin.AdminService.CreateTranscriptRequest:input_type -> admin.TranscriptRequest
	10, // 3: admin.AdminService.ViewQueue:input_type -> admin.Empty
	1,  // 4: admin.AdminService.JoinQueue:input_type -> admin.QueueRequest
	4,  // 5: admin.AdminService.RegisterRetake:input_type -> admin.RetakeRequest
	5,  // 6: admin.AdminService.GetSchedule:input_type -> admin.ScheduleRequest
	8,  // 7: admin.AdminService.UpdateSchedule:input_type -> admin.UpdateScheduleRequest
	9,  // 8: admin.AdminService.SubmitCertificateRequest:input_type -> admin.CertificateRequest
	10, // 9: admin.AdminService.CreateTranscriptRequest:output_type -> admin.Empty
	2,  // 10: admin.AdminService.ViewQueue:output_type -> admin.QueueList
	10, // 11: admin.AdminService.JoinQueue:output_type -> admin.Empty
	10, // 12: admin.AdminService.RegisterRetake:output_type -> admin.Empty
	6,  // 13: admin.AdminService.GetSchedule:output_type -> admin.ScheduleResponse
	10, // 14: admin.AdminService.UpdateSchedule:output_type -> admin.Empty
	10, // 15: admin.AdminService.SubmitCertificateRequest:output_type -> admin.Empty
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
